### ISSUE TITLE
Unrendered Images in issue description

### ISSUE THREAD

**Issue by gabeusse** [fulstech/markin#30]
When using the plugin on the newest version of JIRA, sometimes inlined images are not rendered, and the following exception appears on the JIRA log files. To get this error, I created an issue description like the following:

Description text

![test][link_to_image_in_internal_server]

```
2017-07-11 13:21:00,119 Sending mailitem com.atlassian.jira.mail.IssueMailQueueItem@4299c58[issue=com.atlassian.jira.issue.IssueImpl@67609e[id=32926,summary=
Need to redesign DLP and PLP ratio controlling low trip count execution relation,key=ST-2348,created=2017-05-18 14:38:15.808,updated=2017-07-11 13:09:45.833,
assignee=eusse(eusse),reporter=(ommited)],remoteUser=(ommited),notificationType=All_Watchers,eventTypeId=6,templateId=6] WARN anonymous    Ma
il Queue Service [c.a.jira.mail.IssueTemplateContext] Unable to produce rendered version of the comment for the issue XXXX.
java.lang.IllegalStateException: java.lang.NullPointerException
        at com.fulstech.markin.renderer.MarkinRenderer.render(MarkinRenderer.java:39)
        at com.atlassian.jira.issue.managers.DefaultRendererManager.getRenderedContent(DefaultRendererManager.java:132)
        at com.atlassian.jira.mail.IssueTemplateContext.getCommentParams(IssueTemplateContext.java:195)
        at com.atlassian.jira.mail.IssueTemplateContext.getTemplateParams(IssueTemplateContext.java:101)
        at com.atlassian.jira.mail.IssueMailQueueItem.getIssueContextParams(IssueMailQueueItem.java:157)
        at com.atlassian.jira.mail.IssueMailQueueItem.send(IssueMailQueueItem.java:127)
        at com.atlassian.mail.queue.MailQueueImpl.sendBufferUnderLock(MailQueueImpl.java:103)
        at com.atlassian.mail.queue.MailQueueImpl.sendBuffer(MailQueueImpl.java:56)
        at com.atlassian.jira.mail.JiraMailQueue$1.apply(JiraMailQueue.java:51)
        at com.atlassian.jira.mail.JiraMailQueue$1.apply(JiraMailQueue.java:48)
        at com.atlassian.jira.util.velocity.DefaultVelocityRequestContextFactory.runWithStaticBaseUrl(DefaultVelocityRequestContextFactory.java:110)
        at com.atlassian.jira.util.DefaultBaseUrl.runWithStaticBaseUrl(DefaultBaseUrl.java:50)
        at com.atlassian.jira.mail.JiraMailQueue.sendBuffer(JiraMailQueue.java:48)
        at com.atlassian.jira.service.services.mail.MailQueueService.run(MailQueueService.java:21)
        at com.atlassian.jira.service.JiraServiceContainerImpl.run(JiraServiceContainerImpl.java:61)
        at com.atlassian.jira.service.ServiceRunner.runService(ServiceRunner.java:62)
        at com.atlassian.jira.service.ServiceRunner.runServiceId(ServiceRunner.java:44)
        at com.atlassian.jira.service.ServiceRunner.runJob(ServiceRunner.java:32)
        at com.atlassian.scheduler.core.JobLauncher.runJob(JobLauncher.java:153)
        at com.atlassian.scheduler.core.JobLauncher.launchAndBuildResponse(JobLauncher.java:118)
        at com.atlassian.scheduler.core.JobLauncher.launch(JobLauncher.java:97)
        at com.atlassian.scheduler.caesium.impl.CaesiumSchedulerService.launchJob(CaesiumSchedulerService.java:443)
        at com.atlassian.scheduler.caesium.impl.CaesiumSchedulerService.executeLocalJob(CaesiumSchedulerService.java:410)
        at com.atlassian.scheduler.caesium.impl.CaesiumSchedulerService.executeQueuedJob(CaesiumSchedulerService.java:388)
        at com.atlassian.scheduler.caesium.impl.CaesiumSchedulerService$1.consume(CaesiumSchedulerService.java:285)
        at com.atlassian.scheduler.caesium.impl.CaesiumSchedulerService$1.consume(CaesiumSchedulerService.java:282)
        at com.atlassian.scheduler.caesium.impl.SchedulerQueueWorker.executeJob(SchedulerQueueWorker.java:65)
        at com.atlassian.scheduler.caesium.impl.SchedulerQueueWorker.executeNextJob(SchedulerQueueWorker.java:59)
        at com.atlassian.scheduler.caesium.impl.SchedulerQueueWorker.run(SchedulerQueueWorker.java:34)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at com.fulstech.markin.setting.SettingRepository.getUserKey(SettingRepository.java:74)
        at com.fulstech.markin.setting.SettingRepository.getFontSettingKey(SettingRepository.java:67)
        at com.fulstech.markin.setting.SettingRepository.getFont(SettingRepository.java:26)
        at com.fulstech.markin.renderer.MarkinRenderer.getParameters(MarkinRenderer.java:47)
        at com.fulstech.markin.renderer.MarkinRenderer.render(MarkinRenderer.java:34)
```

Best Regards,

Juan Eusse

**Comment by fulstech** [comment]
@gabeusse,

This bug has been fixed in version 9.0.4.

Thank you so much for using our product. If you have any other request, don't hesitate to let us know. Once again we apologize for any trouble this bug has caused.

Fulstech Support
